"""empty message

Revision ID: 3ebf58f4bbae
Revises: 84a89fe0b190
Create Date: 2019-09-16 17:51:14.553046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebf58f4bbae'
down_revision = '84a89fe0b190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ticket_user_id_fkey', 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('ticket_user_id_fkey', 'ticket', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
