"""empty message

Revision ID: 413fbf026eca
Revises: c6b8fca64d9d
Create Date: 2019-09-13 16:37:29.202537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '413fbf026eca'
down_revision = 'c6b8fca64d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.DateTime(), nullable=False))
    op.alter_column('events', 'time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('events', 'date')
    # ### end Alembic commands ###
