"""empty message

Revision ID: 4e83ee5348f7
Revises: 56ff5d0097c0
Create Date: 2019-09-12 15:44:21.772647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e83ee5348f7'
down_revision = '56ff5d0097c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('events', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('time', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('venue_address', sa.String(), nullable=False))
    op.add_column('events', sa.Column('venue_city', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'venue_city')
    op.drop_column('events', 'venue_address')
    op.drop_column('events', 'time')
    op.drop_column('events', 'price')
    op.drop_column('events', 'image_url')
    op.drop_table('users')
    # ### end Alembic commands ###
