"""empty message

Revision ID: 84a89fe0b190
Revises: 2f006dc658c5
Create Date: 2019-09-16 17:17:58.659496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a89fe0b190'
down_revision = '2f006dc658c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'order_id')
    # ### end Alembic commands ###
