"""empty message

Revision ID: 9d378429e834
Revises: d0f2811836c8
Create Date: 2019-09-14 09:45:11.431614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d378429e834'
down_revision = 'd0f2811836c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('organizer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'organizers', ['organizer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'organizer_id')
    # ### end Alembic commands ###
