"""empty message

Revision ID: c6b8fca64d9d
Revises: 254a40fecac4
Create Date: 2019-09-13 12:10:40.076144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b8fca64d9d'
down_revision = '254a40fecac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organizer', sa.Column('is_org', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_org', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_org')
    op.drop_column('organizer', 'is_org')
    op.drop_table('ticket')
    # ### end Alembic commands ###
