"""empty message

Revision ID: d0f2811836c8
Revises: 7d9beb842964
Create Date: 2019-09-14 09:44:39.847654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f2811836c8'
down_revision = '7d9beb842964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('events', 'organizer_id')
    op.add_column('ticket', sa.Column('ticket_type_id', sa.Integer(), nullable=False))
    op.alter_column('ticket', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'ticket', 'ticket_type', ['ticket_type_id'], ['id'])
    op.alter_column('users', 'is_org',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_org',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.alter_column('ticket', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('ticket', 'ticket_type_id')
    op.add_column('events', sa.Column('organizer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('organizers')
    # ### end Alembic commands ###
