"""empty message

Revision ID: ef3ee90298f1
Revises: dbf1929ab3d5
Create Date: 2019-09-13 22:55:06.120866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3ee90298f1'
down_revision = 'dbf1929ab3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('organizer')
    op.drop_constraint('events_organizer_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'organizers', ['organizer_id'], ['id'])
    op.add_column('ticket', sa.Column('ticket_type_id', sa.Integer(), nullable=False))
    op.alter_column('ticket', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'ticket', 'ticket_type', ['ticket_type_id'], ['id'])
    op.alter_column('users', 'is_org',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_org',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.alter_column('ticket', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('ticket', 'ticket_type_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_organizer_id_fkey', 'events', 'organizer', ['organizer_id'], ['id'])
    op.create_table('organizer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_org', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='organizer_pkey')
    )
    op.drop_table('organizers')
    # ### end Alembic commands ###
